services:
  mock-oneall:
    build: .
    command: ["uvicorn", "mock_login.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "${PORT:-8089}", "--reload"]
    ports:
      - "${PORT:-8089}:${PORT:-8089}"
    volumes:
      - ./config:/app/config
    environment:
      - CONFIG_PATH=/app/config/users.yaml
      - PORT=${PORT:-8089}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8089}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
