- user_token: "123e4567-test-user-1abc-426614174000"
  identity_token: "test-identity-1"
  id: "1"
  provider: "github"
  username: "testuser1"
  display_name: "Test User 1"
  email: "test1@example.com"
- user_token: "123e4567-test-user-2abc-426614174000"
  identity_token: "test-identity-2"
  id: "2"
  provider: "google"
  username: "testuser2"
  display_name: "Test User 2"
  email: "test2@example.com"
- user_token: "123e4567-test-user-3abc-426614174000"
  identity_token: "test-identity-3"
  id: "3"
  provider: "test_provider"
  username: "testuser3"
  display_name: "Test User 3"
  email: "test3@example.com"
